### PR TITLE
Mattherndon/board update and more

### PR DESCRIPTION
**Pull request by amicableskeptic**
Huge update. Removed Mark and Meri from board and replaced them with Elise and Lauren. Updated all committee membership info. Added a new bio and reordered all board stuff to be alphabetical by last name. Added new 2019 banner images and replaced Spring Banquet ad with Fall Dinner.

### CODE REVIEW

**Comment by fortynachos** [comment]
@NickHeiner & @amicableskeptic, do either of you have merge permissions?  If not lmk and I'll merge when ready (and look into to adding you as well).

**Comment by amicableskeptic** [comment]
I think we both do, I just try and avoid merging my own changes unless it's
an emergency. These aren't emergency, but we do have a board meeting at 9
tonight and it would be nice to have them deployed before then, but not
required.

**Comment by fortynachos** [comment]
Legit -- if you're ready to merge / deploy, I think any of us can take care of it then.  I don't have much context on the details of the changes, but just @ me if you want me to do anything specifically.

**Comment by amicableskeptic** [comment]
I think it’s good to go. If you do a quick once over and agree then please
merge and deploy to live.

**Comment by fortynachos** [comment]
Thanks for all the docs updates.  LGTM

**Comment by fortynachos** [comment]
Can someone do me a favor and run `npm run deploy` with the latest master?  I don't think I have the right permissions to push to cornellfencing/cornellfencing.github.io and am getting rejected by that remote.  Either that or I'm just doing something stupid ¯\_(ツ)_/¯

**Comment by amicableskeptic** [comment]
I think that something is wrong with this merge. I think the issue is that you put it into https://github.com/fortynachos/cornellfencingv4 when it should have gone into https://github.com/cornellfencing/cornellfencing.github.io instead. I just pulled the latest from https://github.com/cornellfencing/cornellfencing.github.io and confirmed that my changes weren't there. I think the way to fix this is to remerge these changes into the right place, but I'm going to wait for Nick to weigh in before I go and do that and accidentally make something worse. @NickHeiner what say ye?

**Comment by NickHeiner** [comment]
Hi. Sorry for the delay on this. Yes, the problem is that this PR was to the wrong repo. The fact that the commit history included commits from 2017 was a clue :smile:

image

I'll deploy these changes to the real site. Mike, you maybe should just delete your fork, or rename it to `-do-not-use`, to avoid confusion like this going forward.

**Comment by NickHeiner** [comment]
This is what the PR should have looked like, for future reference: https://github.com/fortynachos/cornellfencingv4/pull/20

**Comment by NickHeiner** [comment]
NEVER MIND I FUCKED IT UP TOO IVE BEEN BAMBOOZLED AGAIN THANKS OBAMA

Mike's repo is set as the parent, but we've been treating https://github.com/cornellfencing/cornellfencing.github.io/ as the parent. Thus, GH defaults to sending the PR to Mike's repo, which is not what we want. Mike may have perms to declare https://github.com/cornellfencing/cornellfencing.github.io as the new parent.

**Comment by NickHeiner** [comment]
This change is now deployed.

**Pull request merged**
